const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const net=require('node:net');
const {Sessions}=require('../src/sessions.cjs');
const {Files}=require('../src/files.cjs');
const {fixture}=require('./ssh-fixture.cjs');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,message,ms=15000){const start=Date.now();while(Date.now()-start<ms){if(await fn())return;await sleep(100);}throw new Error('Timeout: '+message);}
module.exports=async({app,win,sessions,files,store})=>{
  const base=path.join(__dirname,'../test-results');await fs.mkdir(base,{recursive:true});
  store.data.profiles=[];store.data.hosts={};store.data.workspaces=[];store.data.settings.language='tr';store.write();require('../src/i18n.cjs').setLanguage('tr');
  await win.loadFile(path.join(__dirname,'../dist/index.html'));
  const errors=[];win.webContents.on('console-message',event=>{if(event.level==='error'){errors.push(event.message);console.error('RENDERER:',event.message);}});
  await until(()=>win.webContents.executeJavaScript('Boolean(window.__lumaReady)'),'renderer ready');
  console.log('Renderer ready'); await sleep(500);
  assert.equal(await win.webContents.executeJavaScript('document.querySelectorAll("#shell-list button").length'),4);
  await fs.writeFile(path.join(base,'welcome.png'),(await win.webContents.capturePage()).toPNG());
  console.log('Welcome captured');
  await win.webContents.executeJavaScript('document.getElementById("settings-button").click()');
  await until(()=>win.webContents.executeJavaScript('document.getElementById("modal").open'),'settings');
  assert.equal(await win.webContents.executeJavaScript('document.querySelector("select[name=promptTheme]").options.length'),4);
  assert.equal(await win.webContents.executeJavaScript('document.querySelector("input[name=promptGit]").checked'),true);
  assert.ok(await win.webContents.executeJavaScript('document.querySelectorAll(".settings-nav button").length >= 4'));
  await sleep(300);
  await fs.writeFile(path.join(base,'settings.png'),(await win.webContents.capturePage()).toPNG());
  console.log('Settings captured');
  await win.webContents.executeJavaScript('document.getElementById("modal").close(); document.getElementById("add-connection").click()');
  await until(()=>win.webContents.executeJavaScript('Boolean(document.querySelector("textarea[name=forwards]"))'),'port forwarding profile control');
  await win.webContents.executeJavaScript('document.getElementById("modal").close(); document.getElementById("new-terminal").click()');
  await until(()=>win.webContents.executeJavaScript('document.querySelectorAll(".tab").length === 1'),'PowerShell tab');
  const local=[...sessions.items.values()].find(s=>s.kind==='local');assert.ok(local?.pty);
  console.log('Local terminal created');
  let output='';const listener=local.pty.onData(data=>output+=data);sessions.input(local.id,"Write-Output ('LUMA' + '_ELECTRON_PTY_OK')\r");await until(()=>output.includes('LUMA_ELECTRON_PTY_OK'),'ConPTY output');listener.dispose();
  await sleep(500);await fs.writeFile(path.join(base,'terminal.png'),(await win.webContents.capturePage()).toPNG());
  console.log('Local terminal captured');
  await win.webContents.executeJavaScript('document.getElementById("new-terminal").click()');await until(()=>sessions.items.size===2,'second terminal');
  await win.webContents.executeJavaScript('document.getElementById("split-button").click()');
  assert.equal(await win.webContents.executeJavaScript('document.querySelectorAll(".terminal-pane:not([hidden])").length'),2);
  await require('./directory-language.cjs')({win,sessions,store,base,firstId:local.id});
  await require('./performance.cjs').local({win,sessions,id:local.id,base});
  const fixtureRoot=await fs.mkdtemp(path.join(base,'fixture-'));
  const remoteRoot=path.join(fixtureRoot,'remote'),uploads=path.join(fixtureRoot,'uploads'),downloads=path.join(fixtureRoot,'downloads');
  for(const dir of [remoteRoot,uploads,downloads])await fs.mkdir(dir,{recursive:true});
  await fs.writeFile(path.join(remoteRoot,'.hidden'),'hidden');await fs.writeFile(path.join(remoteRoot,'hello.txt'),'hello SSH');
  await fs.writeFile(path.join(uploads,'Türkçe dosya.txt'),'round trip ✓ '.repeat(10000));
  const fixtureServer=await fixture(remoteRoot);let checks=0,sshEvents=[];
  const echoServer=net.createServer(socket=>socket.pipe(socket));await new Promise(resolve=>echoServer.listen(0,'127.0.0.1',resolve));
  const portProbe=net.createServer();await new Promise(resolve=>portProbe.listen(0,'127.0.0.1',resolve));const forwardPort=portProbe.address().port;await new Promise(resolve=>portProbe.close(resolve));
  const testSessions=new Sessions(store,e=>sshEvents.push(e),async()=>{checks++;return true;});const testFiles=new Files(testSessions,()=>{},async()=>true);
  try {
    store.saveProfile({name:'Test SSH',host:'127.0.0.1',port:fixtureServer.port,username:'tester',password:'fixture-secret'});
    const p=store.data.profiles.at(-1);assert.ok(p.secret);assert.ok(!(await fs.readFile(store.file,'utf8')).includes('fixture-secret'));
    const a=await testSessions.open({kind:'ssh',profileId:p.id});assert.equal(checks,1);assert.equal(a.sftp,true);
    const entries=await testFiles.list(a.id,'/');assert.ok(entries.some(e=>e.name==='.hidden'));assert.ok(entries.some(e=>e.name==='hello.txt'));
    testSessions.input(a.id,'round-trip\r');await until(()=>sshEvents.some(e=>e.type==='data'&&e.data.includes('echo:round-trip')),'SSH shell echo');
    await testFiles.upload(a.id,[path.join(uploads,'Türkçe dosya.txt')],'/');await testFiles.download(a.id,['/Türkçe dosya.txt'],downloads);
    assert.deepEqual(await fs.readFile(path.join(uploads,'Türkçe dosya.txt')),await fs.readFile(path.join(downloads,'Türkçe dosya.txt')));
    await testFiles.mutate(a.id,'mkdir','/','nested');await testFiles.mutate(a.id,'rename','/hello.txt','renamed.txt');assert.ok((await testFiles.list(a.id,'/')).some(e=>e.name==='renamed.txt'));
    await testFiles.mutate(a.id,'delete','/renamed.txt');assert.ok(!(await testFiles.list(a.id,'/')).some(e=>e.name==='renamed.txt'));
    const b=await testSessions.open({kind:'ssh',profileId:p.id});assert.equal(checks,1);testSessions.close(b.id);
    await assert.rejects(()=>testSessions.open({kind:'ssh',profileId:p.id,password:'incorrect-password'}));
    const keyPath=path.join(fixtureRoot,'id_rsa');await fs.writeFile(keyPath,fixtureServer.userKey);
    store.saveProfile({name:'Key SSH',host:'127.0.0.1',port:fixtureServer.port,username:'tester',auth:'key',privateKeyPath:keyPath});
    const keySession=await testSessions.open({kind:'ssh',profileId:store.data.profiles.at(-1).id});assert.equal(keySession.kind,'ssh');testSessions.close(keySession.id);
    store.saveProfile({name:'Tunnel SSH',host:'127.0.0.1',port:fixtureServer.port,username:'tester',password:'fixture-secret',forwards:`${forwardPort}:127.0.0.1:${echoServer.address().port}`});
    const tunnel=await testSessions.open({kind:'ssh',profileId:store.data.profiles.at(-1).id});assert.equal(tunnel.forwards.length,1);
    const tunneled=await new Promise((resolve,reject)=>{const socket=net.connect(forwardPort,'127.0.0.1',()=>socket.write('LUMA_TUNNEL_OK'));let value='';socket.on('data',data=>{value+=data;if(value.includes('LUMA_TUNNEL_OK')){socket.end();resolve(value);}});socket.on('error',reject);setTimeout(()=>{socket.destroy();reject(new Error('Tunnel timeout'));},5000).unref();});assert.match(tunneled,/LUMA_TUNNEL_OK/);testSessions.close(tunnel.id);
    await fs.mkdir(path.join(uploads,'folder'));await fs.writeFile(path.join(uploads,'folder','child.txt'),'recursive copy');
    await testFiles.upload(a.id,[path.join(uploads,'folder')],'/');await testFiles.download(a.id,['/folder'],downloads);assert.equal(await fs.readFile(path.join(downloads,'folder','child.txt'),'utf8'),'recursive copy');
    store.data.hosts['127.0.0.1:'+fixtureServer.port]='SHA256:changed';store.write();await assert.rejects(()=>testSessions.open({kind:'ssh',profileId:p.id}));assert.equal(checks,1);
    delete store.data.hosts['127.0.0.1:'+fixtureServer.port];store.write();
    // Open an SSH tab through the real renderer IPC after trusting the fixture host.
    await testSessions.open({kind:'ssh',profileId:p.id});
    await win.loadFile(path.join(__dirname,'../dist/index.html'));await until(()=>win.webContents.executeJavaScript('Boolean(window.__lumaReady)'),'reload');
    assert.equal(await win.webContents.executeJavaScript('document.documentElement.lang'),'en');
    await win.webContents.executeJavaScript('document.querySelector("[data-profile]").click()');
    await until(()=>win.webContents.executeJavaScript('document.querySelectorAll("#remote-files .file-row").length >= 2'),'SFTP UI');
    const rendererSSH=[...sessions.items.values()].find(s=>s.kind==='ssh');
    const staged=await win.webContents.executeJavaScript(`window.luma.filesDrag(${JSON.stringify(rendererSSH.id)},'/Türkçe dosya.txt')`);
    assert.deepEqual(await fs.readFile(staged.local),await fs.readFile(path.join(uploads,'Türkçe dosya.txt')));
    await sleep(300);
    await fs.writeFile(path.join(base,'ssh.png'),(await win.webContents.capturePage()).toPNG());
    await require('./performance.cjs').remote({win,sessions,id:rendererSSH.id,base,root:remoteRoot,fixture:fixtureServer,files});
    assert.deepEqual(errors,[]);
    await fs.writeFile(path.join(base,'smoke.json'),JSON.stringify({passed:true,checks:['renderer startup','settings UI','real Electron ConPTY PowerShell','multiple sessions and split view','Windows DPAPI encrypted storage','SSH password and key authentication','SSH local port forwarding','incorrect password rejection','SSH terminal round trip','hidden remote files','SFTP upload/download binary equality','recursive folder transfer','native drag staging','mkdir/rename/delete','known host reuse','changed host rejection','renderer SSH + SFTP integration'],rendererErrors:errors},null,2));
    console.log('SMOKE PASS: renderer, ConPTY, DPAPI, SSH tunnels, host verification, SFTP and split sessions');
  }finally{testSessions.closeAll();sessions.closeAll();fixtureServer.close();echoServer.close();await sleep(700);console.log('Cleanup complete');}
};
