const fs = require('node:fs');
const path = require('node:path');
const esbuild = require('esbuild');
fs.mkdirSync('dist',{recursive:true});
esbuild.buildSync({ entryPoints:['src/renderer.js'],bundle:true,outfile:'dist/app.js',minify:true,platform:'browser',target:'chrome140' });
fs.copyFileSync('src/index.html','dist/index.html');
fs.copyFileSync('src/styles.css','dist/styles.css');
fs.copyFileSync('src/features.css','dist/features.css');
fs.copyFileSync('node_modules/@xterm/xterm/css/xterm.css','dist/xterm.css');
console.log('LumaTerm renderer built.');
