const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
module.exports=async({app,win,sessions,store})=>{
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  for(let n=0;n<100&&!await win.webContents.executeJavaScript('Boolean(window.__lumaReady)');n++)await sleep(100);
  assert.equal(await win.webContents.executeJavaScript('Boolean(window.__lumaReady)'),true);
  const s=await sessions.open({kind:'local',shell:'powershell.exe'});let output='';
  sessions.get(s.id).pty.onData(data=>output+=data);
  sessions.input(s.id,"Write-Output ('PACKAGE_' + 'PTY_OK')\r");
  for(let n=0;n<100&&!output.includes('PACKAGE_PTY_OK');n++)await sleep(100);
  assert.ok(output.includes('PACKAGE_PTY_OK'));
  assert.match(output,/\x1b\[38;2;/);assert.ok(output.includes('◆')&&output.includes('❯'));
  const directory=path.resolve(app.getPath('userData'));
  sessions.input(s.id,"Set-Location -LiteralPath '"+directory.replace(/'/g,"''")+"'\r");
  for(let n=0;n<100&&sessions.get(s.id).cwd!==directory;n++)await sleep(100);
  assert.equal(sessions.get(s.id).cwd,directory);
  assert.equal(await win.webContents.executeJavaScript('document.querySelector(".feature-cards") === null'),true);
  assert.equal(await win.webContents.executeJavaScript('Boolean(document.getElementById("suggestions-button"))'),true);
  assert.equal(await win.webContents.executeJavaScript('Boolean(document.getElementById("remote-explorer") && document.getElementById("local-explorer"))'),true);
  assert.equal(await win.webContents.executeJavaScript('Boolean(document.getElementById("file-filter"))'),true);
  await win.webContents.executeJavaScript('document.getElementById("settings-button").click()');
  for(let n=0;n<100&&!await win.webContents.executeJavaScript('Boolean(document.querySelector("select[name=language]"))');n++)await sleep(100);
  assert.equal(await win.webContents.executeJavaScript('Boolean(document.querySelector("input[name=suggestions]"))'),true);
  assert.equal(await win.webContents.executeJavaScript('Boolean(document.querySelector(".settings-nav"))'),true);
  await win.webContents.executeJavaScript('document.querySelector("select[name=language]").value="en";document.getElementById("settings-submit").click()');
  for(let n=0;n<100&&!await win.webContents.executeJavaScript('document.documentElement.lang === "en"');n++)await sleep(100);
  assert.equal(await win.webContents.executeJavaScript('document.documentElement.lang'),'en');
  assert.equal(store.decrypt(store.encrypt('test-value')),'test-value');
  sessions.closeAll();await sleep(700);
  await fs.writeFile(path.join(app.getPath('userData'),'package-check.json'),JSON.stringify({passed:true,version:'0.5.0',checks:['packaged renderer','packaged ConPTY DLL','real PowerShell output','colored Git-aware prompt','PowerShell directory tracking','single-context file explorers','file filtering','command suggestions UI','English default UI','DPAPI encryption']},null,2));
  console.log('PACKAGE CHECK PASS');
};
